logicalclocks/livy-chef

templates/default/start-livy.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-445
=> Downloader HOPSWORKS-445

attributes/default.rb, recipes/install.rb
=> HOPSWORKS-481

Berksfile, recipes/default.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-555
=> [HOPSWORKS-555] Missing conda dependency

attributes/default.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-587
=> [HOPSWORKS-598] Upgrade livy version to 0.6.0-incubating-SNAPSHOT

attributes/default.rb, metadata.rb, recipes/default.rb, templates/default/log4j.properties.erb, templates/default/start-livy.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-635
=> [HOPSWORKS-635] Enable log4j logging

Berksfile, metadata.rb, recipes/default.rb, templates/default/livy-consul.hcl.erb, templates/default/livy-health.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
=> [HOPSWORKS-1405] Register livy server with consul

Berksfile
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
=> [HOPSWORKS-1679] pin version of java in Berksfile

Berksfile, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
=> [HOPSWORKS-1679] Pin deps

Karamelfile, recipes/default.rb, templates/default/livy.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1685
=> [HOPSWORKS-1685] Start Livy server after the ResourceManager

templates/default/start-livy.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1709
=> [HOPSWORKS-1709] Add Hadoop jars to Livy classpath

templates/default/livy-consul.hcl.erb, templates/default/livy-health.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1718
=> [HOPSWORKS-1718] Fix bug with health check and register with passing health state

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1709
=> [HOPSWORKS-1709] Increment livy version

attributes/default.rb, metadata.rb, recipes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
=> [HOPSWORKS-1694] run user code in docker

attributes/default.rb, metadata.rb, recipes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
=> [HOPSWORKS-1657] System users x.509 v2

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1904
=> [HOPSWORKS-1904] Add livy user to userscerts group

recipes/default.rb, templates/default/livy.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1933
=> [HOPSWORKS-1933] do not hang if consul not started

templates/default/livy.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units

templates/default/livy.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units (#53)

templates/default/livy.service.erb
fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2292
=> [HOPSWORKS-2292] remove systemd waiting mechanism

attributes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Logs and state to data volume
